#!/usr/bin/env bash
# Install nginx and display string

# update apt packages and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# change the default nginx index.html to display a string
sudo ufw allow 'Nginx HTTP'
sudo chmod +rw /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html


nl="\\\tadd_header X-Served-By \$hostname;"
sudo sed -i -e "/sendfile/i $nl" /etc/nginx/nginx.conf
sudo service nginx reload
