#!/usr/bin/env bash
# Install nginx and display string

# update apt packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start
host=$(cat /etc/hostname)
nl="\\\tadd_header X-Served-By \"$host\";"
sudo sed -i -e "/sendfile/i $nl" /etc/nginx/nginx.conf
sudo service nginx restart
