#!/usr/bin/env bash
# Install nginx and display string

# update apt packages and install nginx
host=$(cat /etc/hostname)
new_config="\\\tadd_header X-Served-By \"$host\";"
file='/etc/nginx/nginx.conf'
sudo sed -i "15i $new_config" $file
sudo service nginx restart
