#!/usr/bin/env bash
# Script that debugs an nginx server that is refusing a connection on port 80
sed -i 's/8080 default/80 default/' /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
