#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -le 10 ]
do
  if [ $i -eq 4 ]
  then
    echo 'bad luck'
  else
    if [ $i -eq 8 ]
    then
      echo 'good luck'
    else
      echo 'Holberton school'
    fi
  fi

  i=$(($i + 1))
done
