#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -le 20 ]
do
  if [ $i -eq 5 ]
  then
    echo 'bad luck from china'
  else
    if [ $i -eq 10 ]
    then
      echo 'back luck from Japan'
    else
      if [ $i -eq 18 ]
      then
        echo 'bad luck from Italy'
      fi
    fi
  fi
  echo "$i"
  i=$((i + 1))
done
