#!/usr/bin/env bash
# Script that Changes the configuration of nginx and apache2 to run as the user nginx

sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
sed -i 's/8080/80/' /etc/apache2/ports.conf
service apache2 restart
service apache2 stop
pkill apache2
chmod +r /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
